### ISSUE TITLE
OpenTTD configure step does not find zlib

### ISSUE THREAD

**Issue by mdeletrain** [Homebrew/homebrew-games#160]
As stated in the tilte, zlib is not found by the configure step :

    checking zlib... not found
    WARNING: zlib was not detected or disabled
    WARNING: OpenTTD doesn't require zlib, but it does mean that many features
    WARNING: (like loading most old savegames/scenarios, loading heightmaps,
    WARNING: using PNG, or using fonts, ...) will be disabled.
    configure: error: no zlib detected

The warning says this disables heightmaps, pngs and fonts...

**Comment by jacknagel** [comment]
closing as stale
