### ISSUE TITLE
Error installing dosbox

### ISSUE THREAD

**Issue by puffpio** [Homebrew/homebrew-games#171]
Attempting to install dosbox gives make errors. Ensured brew update and brew doctor were performed without issues

Console showed:

$ brew install dosbox
==> Installing dosbox from homebrew/homebrew-games
==> Downloading https://downloads.sourceforge.net/project/dosbox/dosbox/0.74/dos
Already downloaded: /Library/Caches/Homebrew/dosbox-0.74.tar.gz
==> ./configure --prefix=/usr/local/Cellar/dosbox/0.74 --mandir=/usr/local/Cella
==> make
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by ainop** [comment]
Hi! Seems like I got into clang crash too: https://gist.github.com/anonymous/08e29cec9da480b74aae

**Comment by mistydemeo** [comment]
Macports carries a couple of clang-related patches, but they're not fixing the segfaults:

* https://trac.macports.org/browser/trunk/dports/emulators/dosbox/files/src__cpu__core_dynrec__risc_x64.h.diff
* https://trac.macports.org/browser/trunk/dports/emulators/dosbox/files/patch-src-fpu-fpu_instructions_x86.h.diff

**Comment by mistydemeo** [comment]
I've seen a few indications that this is a known issue when using the dynamic core in 64-bit mode, but a 32-bit build doesn't help.

**Comment by mistydemeo** [comment]
However, using the `normal` core does work for me - albeit more slowly than it should. This is true with clang and gcc-4.9.

**Comment by imlyc** [comment]
Hi, I got the same crash here,
    
    https://gist.github.com/dd8eeb686f64ee5ce654

Thanks.

**Comment by FabianFrank** [comment]
https://gist.github.com/anonymous/318680cc3913528faba2

**Comment by neoascetic** [comment]
Same issue here

**Comment by mistydemeo** [comment]
Likely addressed via #310.
