### ISSUE TITLE
fuego failed to build on 10.9.5

### ISSUE THREAD

**Issue by tunesmith** [Homebrew/homebrew-games#207]
https://gist.github.com/0cf661a86f726e47a5be

In addition, the formula is for fuego 1.0, while 1.1 is available now.

**Comment by qrohlf** [comment]
#208 should fix this. Fuego 1.1 still won't build with modern boost libraries, however Fuego@HEAD does.

**Comment by milescrabill** [comment]
I finally got around to fixing #208 so it is fit to merge! Should solve your issue tunesmith.

**Comment by tunesmith** [comment]
That's great!  Anything I need to do to encourage the merging process?  So far, 'brew info fuego' still shows 1.0 .
