### ISSUE TITLE
=> build? options not being installed when using --only-dependencies?

### ISSUE THREAD

**Issue by cbeck88** [Homebrew/homebrew-games#238]
Hi,

We made a wesnoth 1.12.3 release recently, and also 1.13.0 development release is imminent. I decided to try to run the homebrew builds, got some odd behavior:

https://travis-ci.org/cbeck88/wesnoth/builds/58850415
https://travis-ci.org/cbeck88/wesnoth/builds/58858821

(The pages you see there are travis logs of bash scripts which ran on OS X machines and tried to invoke homebrew.)

As you can see the first build fails because it doesn't install scons. With the second one, I tweaked travis to explicitly install scons -- then it builds but it doesn't find gettext which is why I thought it must be related to the =>build? option.

I'm not sure if this is a real bug -- maybe you guys decided that --only-dependencies should not install the build-time dependencies? Anyways I'm sure this script used to work so it must be a change in behavior. I thought it couldn't hurt to report.

**Comment by jacknagel** [comment]
Since the formula has bottles, build dependencies are not installed unless you use `--build-from-source` or `--build-bottle`.

**Comment by cbeck88** [comment]
I see, thanks for explaining it.
