### ISSUE TITLE
nethack4: what to do with HEAD?

### ISSUE THREAD

**Issue by L2G** [Homebrew/homebrew-games#247]
The nethack4 formula has its HEAD build defined as the Git repo at https://gitorious.org/nitrohack/ais523.git, branch "nicehack".

Gitorious has announced that it's shutting down at the end of May, and a message on the Git repo above is directing users to use http://nethack4.org/media/nethack4.git instead. I'm not able to connect to that URL, so I haven't made the change.

(Also see Homebrew/homebrew#39176 for the core formulæ that will be affected by the Gitorious closure.)

**Comment by mistydemeo** [comment]
Hm, I'm getting a 403 at that URL too. I'll try contacting the author.

**Comment by mistydemeo** [comment]
Actually, never mind - I'm able to clone it using `git` (it just gives a 403 in the browser). Are you able to `git clone http://nethack4.org/media/nethack4.git`?

**Comment by L2G** [comment]
I don't think I could when I tried it a couple of days ago. Trying it now, but it is slow as slugs.

**Comment by L2G** [comment]
Yep. It's slow as slugs when I clone it, but I can clone it.

**Comment by mistydemeo** [comment]
Yeah, it was slow for me too. At least it works!
