### ISSUE TITLE
freeciv/2.5.0_2 does not support most keyboard shortcuts

### ISSUE THREAD

**Issue by sam-s** [Homebrew/homebrew-games#285]
E.g., from the initial screen, `Cmd-N` should start new game, `Cmd-L` should load a game.
From the game screen, `Cmd-G` does not enter the `Game` menu &c &c &c....

**Comment by dunn** [comment]
And you've confirmed this only happens when freeciv is installed with Homebrew?

**Comment by sam-s** [comment]
I am afraid homebrew is the only way I can install freeciv.
Please do not hesitate to forward the bug report upstream.
PS. also, the existing shortcuts are inconsistent (`Cmd-S` for save vs `Ctrl-E` for edit).

**Comment by dunn** [comment]
If you were willing to open an upstream issue, we'd be very grateful! And if the developers provide a patch we can apply to the current release, then we can update our formula to include it.

**Comment by sam-s** [comment]
https://gna.org/bugs/index.php?23719

**Comment by mistydemeo** [comment]
Which client(s) have you tried? Does this happen in both the SDL and GTK+ clients?

**Comment by sam-s** [comment]
gtk+; I could never get sdl to work

**Comment by sam-s** [comment]
upstream says that they don't use macos so this must be a mac-specific gtk+ issue
