### ISSUE TITLE
xboard won't start: Symbol not found: _cairo_xlib_surface_create

### ISSUE THREAD

**Issue by fjarlq** [Homebrew/homebrew-games#296]
I suppose this is due to commit [f4005f1][1] -- cairo is no longer built with xlib support.

Hmm, maybe xboard should be built with GTK anyway, since that's now stable in xboard 4.8.0, and the xboard folks consider the Xaw interface "obsolete": http://www.gnu.org/software/xboard/whats_new/4.8.0/

    $ brew update
    Already up-to-date.
    $ brew upgrade
    $ brew doctor
    Your system is ready to brew.
    $ brew install xboard
    brew install xboard
    ==> Installing xboard from homebrew/homebrew-games
    ==> Downloading https://homebrew.bintray.com/bottles-games/xboard-4.7.3.yosemite.bottle.tar.gz
    Already downloaded: /Library/Caches/Homebrew/xboard-4.7.3.yosemite.bottle.tar.gz
    ==> Pouring xboard-4.7.3.yosemite.bottle.tar.gz
    🍺  /usr/local/Cellar/xboard/4.7.3: 154 files, 3.3M
    $ xboard
    dyld: lazy symbol binding failed: Symbol not found: _cairo_xlib_surface_create
      Referenced from: /usr/local/bin/xboard
      Expected in: /usr/local/lib/libcairo.2.dylib
    
    dyld: Symbol not found: _cairo_xlib_surface_create
      Referenced from: /usr/local/bin/xboard
      Expected in: /usr/local/lib/libcairo.2.dylib
    
    [1]    3554 trace trap  xboard
    $ brew info xboard
    homebrew/games/xboard: stable 4.7.3 (bottled)
    https://www.gnu.org/software/xboard/
    /usr/local/Cellar/xboard/4.7.3 (154 files, 3.3M) *
      Poured from bottle
    From: https://github.com/homebrew/homebrew-games/blob/master/xboard.rb
    ==> Dependencies
    Build: pkg-config ✔
    Required: gettext ✔, cairo ✔, librsvg ✔
    Recommended: fairymax ✔
    ==> Options
    --without-fairymax
    	Build without fairymax support

[1]: https://github.com/Homebrew/homebrew/commit/f4005f1412a32699823106ff5288312d2fedc02a

**Comment by dunn** [comment]
If xboard can be built against GTK instead of X11, then we should switch it over, yeah.  Are you interested in opening a PR?  Take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by fjarlq** [comment]
Yep, this is fixed now. Thanks.
