### ISSUE TITLE
fceux install failed

### ISSUE THREAD

**Issue by w359405949** [Homebrew/homebrew-games#345]
==> Downloading https://downloads.sourceforge.net/project/fceultra/Source%20Code/2.2.2%20src/fceux-2.2.2.src.tar.gz
Already downloaded: /Library/Caches/Homebrew/fceux-2.2.2.tar.gz
==> Patching
patching file SConstruct
patching file SConstruct
patching file src/drivers/sdl/SConscript
patching file src/drivers/sdl/gui.cpp
patching file src/drivers/sdl/sdl-video.cpp
==> /usr/local/opt/scons/bin/scons GTK=0 GTK3=1
#include <gd.h>
         ^
1 error generated.
scons: *** [src/drivers/videolog/nesvideos-piece.o] Error 1
scons: building terminated because of errors.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-games/issues

**Comment by dunn** [comment]
Could you post `brew gist-logs fceux`, please?

**Comment by mistydemeo** [comment]
Closing due to lack of response, but please reopen if you're still having issues. If you are, please include the logs!
