### ISSUE TITLE
brew install xu4 failed

### ISSUE THREAD

**Issue by TinSoldier6** [Homebrew/homebrew-games#378]
https://gist.github.com/7fdfb7cf57314c826008

Running OS X Yosemite 10.10.5. Xcode 6.4 (6E35b)

Last lines:
```
==> make bundle -f Makefile.macosx SYSROOT=/Applications/Xcode.app/Contents/Developer/Platforms/
_LIBCPP_FUNC_VIS string to_string(long double __val);
                        ^
1 error generated.
make: *** [person.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by tomyun** [comment]
I had the same problem with the current revision (2099), but it seems to get fixed in the latest revision (3088). Maybe you could try installing `HEAD` or the updated formula submitted above.

**Comment by mistydemeo** [comment]
Should be fixed by 625f1a907c8089f4b38c7c29ac98676c24069f9d - can you retry?

**Comment by TinSoldier6** [comment]
I downloaded the updated xu4.rb last night and it worked. Thanks!

**Comment by mistydemeo** [comment]
Great, glad to hear it!
