### ISSUE TITLE
mame incomplete installation?

### ISSUE THREAD

**Issue by CRP** [Homebrew/homebrew-games#394]
Hi, currently the mame formula installs the binary and man page. Should it also install latest versions of the content of folders such as hash, hlsl, samples, keymaps etc.? These are needed for the correct functioning of mame, but currently need to be downloaded/updated manually.

**Comment by dunn** [comment]
We'd be happy to take a look at a pull request!  See https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by mistydemeo** [comment]
As of #413, these extra files are installed in `share/mame`.
