### ISSUE TITLE
Update SuperTux to version 0.3.5a

### ISSUE THREAD

**Issue by tobbi** [Homebrew/homebrew-games#400]
SuperTux 0.3.5a, released on May 3. Download from https://github.com/SuperTux/supertux/releases

**Comment by dunn** [comment]
Is it a stable version? If not we can add a development version to the formula.  If you're interesting in opening a PR, take a look at https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by tobbi** [comment]
0.3.5a is a development version. Anyway, I will try to create a PR tomorrow.

**Comment by tomyun** [comment]
I submitted #342 for adding 0.3.5a `devel` version, but somehow it didn't build on Mavericks. It'd be nice if you could have a look at the formula and build logs there.

**Comment by bfontaine** [comment]
Closing in favor of #342.
