### ISSUE TITLE
Segmentation Fault: 11 in nethack when manually selecting character role

### ISSUE THREAD

**Issue by patrickmortensen** [Homebrew/homebrew-games#462]
When trying to create a new save in nethack, when asked "Shall I pick a character's race, role, gender and alignment for you? [ynq]" selecting 'n' and choosing the character role manually results in a segmentation fault. Allowing it to select the character role automatically does not result in an issue however.

**Comment by patrickmortensen** [comment]
just occurred to me that nobody here can do anything about it as far as i know, as this repo it just the download scripts for homebrew. Don't mind me, it's been a long week...

**Comment by mistydemeo** [comment]
We're likely going to be upgrading to Nethack 3.6.0 soon - hopefully that'll resolve the issue for you!
