### ISSUE TITLE
brew install homebrew/games/cataclysm --HEAD 

### ISSUE THREAD

**Issue by superwg1984** [Homebrew/homebrew-games#484]
brew install homebrew/games/cataclysm --HEAD
==> Installing cataclysm from homebrew/games
==> Cloning https://github.com/CleverRaven/Cataclysm-DDA.git
Updating /Library/Caches/Homebrew/cataclysm--git
==> Checking out branch master
==> make NATIVE=osx RELEASE=1 CXX=clang++ LD=clang++ CXXFLAGS=  CLANG=1
Last 15 lines from /Users/wanggeng/Library/Logs/Homebrew/cataclysm/01.make:
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DLOCALIZE  -c src/wincurse.cpp -o obj/wincurse.o
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DLOCALIZE  -c src/wish.cpp -o obj/wish.o
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DLOCALIZE  -c src/worldfactory.cpp -o obj/worldfactory.o
Cannot run an astyle check, your system either does not have astyle, or it is too old.
clang++  -DRELEASE -DMACOSX -DGIT_VERSION -DLOCALIZE  -c src/version.cpp -o obj/version.o
clang++  -o cataclysm obj/action.o obj/active_item_cache.o obj/activity_handlers.o obj/activity_item_handling.o obj/addiction.o obj/advanced_inv.o obj/ammo.o obj/animation.o obj/armor_layers.o obj/artifact.o obj/auto_pickup.o obj/basecamp.o obj/bionics.o obj/bodypart.o obj/calendar.o obj/cata_tiles.o obj/cata_utility.o obj/catacharset.o obj/catalua.o obj/char_validity_check.o obj/character.o obj/clzones.o obj/color.o obj/computer.o obj/construction.o obj/craft_command.o obj/crafting.o obj/crafting_gui.o obj/creature.o obj/creature_tracker.o obj/cursesport.o obj/damage.o obj/debug.o obj/defense.o obj/dependency_tree.o obj/editmap.o obj/effect.o obj/event.o obj/faction.o obj/field.o obj/filesystem.o obj/game.o obj/gamemode.o obj/help.o obj/iexamine.o obj/init.o obj/input.o obj/inventory.o obj/inventory_ui.o obj/item.o obj/item_action.o obj/item_factory.o obj/item_group.o obj/item_location.o obj/itype.o obj/iuse.o obj/iuse_actor.o obj/iuse_software.o obj/iuse_software_kitten.o obj/iuse_software_minesweeper.o obj/iuse_software_snake.o obj/iuse_software_sokoban.o obj/json.o obj/lightmap.o obj/line.o obj/live_view.o obj/lua_console.o obj/main.o obj/main_menu.o obj/map.o obj/mapbuffer.o obj/mapdata.o obj/mapgen.o obj/mapgen_functions.o obj/mapgenformat.o obj/mapsharing.o obj/martialarts.o obj/material.o obj/melee.o obj/messages.o obj/mission.o obj/mission_companion.o obj/mission_end.o obj/mission_fail.o obj/mission_place.o obj/mission_start.o obj/missiondef.o obj/mod_manager.o obj/mod_manager_ui.o obj/monattack.o obj/mondeath.o obj/mondefense.o obj/monfaction.o obj/mongroup.o obj/monmove.o obj/monster.o obj/monstergenerator.o obj/mtype.o obj/mutation.o obj/mutation_data.o obj/name.o obj/newcharacter.o obj/nonplayer.o obj/npc.o obj/npcmove.o obj/npctalk.o obj/options.o obj/output.o obj/overmap.o obj/overmapbuffer.o obj/path_info.o obj/pathfinding.o obj/pickup.o obj/player.o obj/player_activity.o obj/posix_time.o obj/profession.o obj/ranged.o obj/recipe_dictionary.o obj/requirements.o obj/rng.o obj/savegame.o obj/savegame_json.o obj/savegame_legacy.o obj/scenario.o obj/sdltiles.o obj/simplexnoise.o obj/skill.o obj/sounds.o obj/speech.o obj/start_location.o obj/submap.o obj/text_snippets.o obj/tileray.o obj/translations.o obj/trap.o obj/trapfunc.o obj/tutorial.o obj/ui.o obj/veh_interact.o obj/veh_type.o obj/vehicle.o obj/vehicle_group.o obj/version.o obj/weather.o obj/weather_data.o obj/weather_gen.o obj/wincurse.o obj/wish.o obj/worldfactory.o  -stdlib=libc++ -mmacosx-version-min=10.5 -lintl -lncurses
ar rcs cataclysm.a obj/action.o obj/active_item_cache.o obj/activity_handlers.o obj/activity_item_handling.o obj/addiction.o obj/advanced_inv.o obj/ammo.o obj/animation.o obj/armor_layers.o obj/artifact.o obj/auto_pickup.o obj/basecamp.o obj/bionics.o obj/bodypart.o obj/calendar.o obj/cata_tiles.o obj/cata_utility.o obj/catacharset.o obj/catalua.o obj/char_validity_check.o obj/character.o obj/clzones.o obj/color.o obj/computer.o obj/construction.o obj/craft_command.o obj/crafting.o obj/crafting_gui.o obj/creature.o obj/creature_tracker.o obj/cursesport.o obj/damage.o obj/debug.o obj/defense.o obj/dependency_tree.o obj/editmap.o obj/effect.o obj/event.o obj/faction.o obj/field.o obj/filesystem.o obj/game.o obj/gamemode.o obj/help.o obj/iexamine.o obj/init.o obj/input.o obj/inventory.o obj/inventory_ui.o obj/item.o obj/item_action.o obj/item_factory.o obj/item_group.o obj/item_location.o obj/itype.o obj/iuse.o obj/iuse_actor.o obj/iuse_software.o obj/iuse_software_kitten.o obj/iuse_software_minesweeper.o obj/iuse_software_snake.o obj/iuse_software_sokoban.o obj/json.o obj/lightmap.o obj/line.o obj/live_view.o obj/lua_console.o obj/main_menu.o obj/map.o obj/mapbuffer.o obj/mapdata.o obj/mapgen.o obj/mapgen_functions.o obj/mapgenformat.o obj/mapsharing.o obj/martialarts.o obj/material.o obj/melee.o obj/mission.o obj/mission_companion.o obj/mission_end.o obj/mission_fail.o obj/mission_place.o obj/mission_start.o obj/missiondef.o obj/mod_manager.o obj/mod_manager_ui.o obj/monattack.o obj/mondeath.o obj/mondefense.o obj/monfaction.o obj/mongroup.o obj/monmove.o obj/monster.o obj/monstergenerator.o obj/mtype.o obj/mutation.o obj/mutation_data.o obj/name.o obj/newcharacter.o obj/nonplayer.o obj/npc.o obj/npcmove.o obj/npctalk.o obj/options.o obj/output.o obj/overmap.o obj/overmapbuffer.o obj/path_info.o obj/pathfinding.o obj/pickup.o obj/player.o obj/player_activity.o obj/posix_time.o obj/profession.o obj/ranged.o obj/recipe_dictionary.o obj/requirements.o obj/rng.o obj/savegame.o obj/savegame_json.o obj/savegame_legacy.o obj/scenario.o obj/sdltiles.o obj/simplexnoise.o obj/skill.o obj/sounds.o obj/speech.o obj/start_location.o obj/submap.o obj/text_snippets.o obj/tileray.o obj/translations.o obj/trap.o obj/trapfunc.o obj/tutorial.o obj/ui.o obj/veh_interact.o obj/veh_type.o obj/vehicle.o obj/vehicle_group.o obj/version.o obj/weather.o obj/weather_data.o obj/weather_gen.o obj/wincurse.o obj/wish.o obj/worldfactory.o
clang: error: invalid deployment target for -stdlib=libc++ (requires OS X 10.7 or later)
make: *** [cataclysm] Error 1
make: *** Waiting for unfinished jobs....
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(cata_tiles.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(cursesport.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(posix_time.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(sdltiles.o) has no symbols
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: file: cataclysm.a(wincurse.o) has no symbols

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/Homebrew/homebrew-games/issues

**Comment by mistydemeo** [comment]
> READ THIS: https://git.io/brew-troubleshooting

Can you read this and post all the requested diagnostics? Thanks!

**Comment by mistydemeo** [comment]
I see the bug; submitted a patch to the developers.

**Comment by mistydemeo** [comment]
Pushed a fix; this works for me now.
