### ISSUE TITLE
mame 0.173: distorted sound for any neogeo game

### ISSUE THREAD

**Issue by yacoob** [Homebrew/homebrew-games#567]
After updating to 0.173 I've found that most (all?) neogeo games that I've tried have terribly broken sound. Check the attached file for an example of distortion in `miexchng` game. 

I'm fairly convinced this problem is specific to homebrew build of mame; this kind of distortion doesn't manifest when you launch the game from the same set of ROMs with a binary build from http://sdlmame.lngn.net/, or with an official 0.173 build of mame64 for windows.

[miexchng.zip](https://github.com/Homebrew/homebrew-games/files/276027/miexchng.zip)

**Comment by yacoob** [comment]
FWIW, manually built brew (`brew install -s mame`) is distortion free. FWIW, here's the set of flags reported by the build process:
```
==> make PTR64=1 USE_LIBSDL=1 USE_SYSTEM_LIB_EXPAT= USE_SYSTEM_LIB_ZLIB=1 USE_SYSTEM_LIB_JPEG=1 USE_SYSTEM_LIB_FLAC=1 USE_SYSTEM_LIB_LUA= USE_SYSTEM_LIB_SQLITE3=1 USE_SYSTEM_LIB_PORTMIDI=1 USE_SYSTEM_LIB_PORTAUDIO=1 USE_SYSTEM_LIB_UV=1
```
plus the build information from `mame -v`
```
Build defines 1:    SDLMAME_UNIX=1 SDLMAME_MACOSX=1 SDLMAME_DARWIN=1
Build defines 1:    LSB_FIRST=1 PTR64=1
SDL/OpenGL defines: SDL_COMPILEDVERSION=2004 USE_OPENGL=1
Compiler defines A: __GNUC__=4 __GNUC_MINOR__=2 __GNUC_PATCHLEVEL__=1 __VERSION__="4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)"
Compiler defines B: __amd64__=1 __x86_64__=1
Compiler defines C: _FORTIFY_SOURCE=2
```

**Comment by tomyun** [comment]
I confirmed this issue with bottled mame 0.173 on El Capitan too. Source built mame had no problem. The only notable difference in the verbose log was clang version, but I have no idea if it could be related with sound glitch.

```
Compiler defines A: __GNUC__=4 __GNUC_MINOR__=2 __GNUC_PATCHLEVEL__=1 __VERSION__="4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.29)"
```

Other than that, dependency list and versions from `otool` looked identical. Probably we should try rebottling it and see how it works.

**Comment by tomyun** [comment]
I found this problem still exists with the recently bottled 0.174. No idea what aspects of server-side bottling could make this happen.

**Comment by ilovezfs** [comment]
It's possible the difference is optimization. Building `-s` and building a bottle do not do exactly the same thing. A more accurate comparison would be to do this:
```
brew uninstall mame
brew install --build-bottle mame
```

**Comment by MikeMcQuaid** [comment]
We'll accept PRs for this but we're not actively working on it at this time.

**Comment by yacoob** [comment]
Leaving this bug opened would probably be more useful, as it'd be easier to find by people who are suffering from the same problem. Then again, I'm not a homebrew member and I'm not the one setting the bug policy for the project :)

**Comment by MikeMcQuaid** [comment]
@yacoob You can still comment on closed issues. Leaving it open sets an expectation that at some point we're going to fix it which is, unfortunately, not realistic.

**Comment by tomyun** [comment]
It seems the issue was somehow caused by build architecture flag.

On my El Capitan box, `--march=core2` was picked up by `--build-bottle` and sound distortion happened. When `--march=native` was used instead by manually editing `hardware.rb`, bottled mame worked fine. I believe this flag is the one picked up by `--build-from-source`. Not setting `--march` by giving `--bottle-arch=dunno` didn't solve the problem.

Currently, I have no idea how this flag would have affected the actual build process nor how we could fix this issue at formula level.

**Comment by tomyun** [comment]
I confirm the latest `mame` 0.178 bottle on Sierra has no sound glitch with `miexchng` rom. No idea if something was fixed upstream or with the new macOS.
