### ISSUE TITLE
cockatrice wrong dependency

### ISSUE THREAD

**Issue by ctrlaltca** [Homebrew/homebrew-games#576]
The cockatrice formula currently depends `libgcrypt`:
```
  if build.with? "server"
    depends_on "libgcrypt"
```

This was correct in the past when cockatrice was linked to Qt4, while the Qt5 version removed this dependency. Since the formula is already using Qt5, the dependency can be removed.

**Comment by dunn** [comment]
Thanks for catching that!

Just to be clear, neither Cockatrice nor Servatrice depends on libgcrypt anymore?

**Comment by ctrlaltca** [comment]
> Just to be clear, neither Cockatrice nor Servatrice depends on libgcrypt anymore?

Exactly. Only servatrice used to depend on libgcrypt, only when compiled with qt4.
Libgcrypt dependency has been removed definitely in https://github.com/Cockatrice/Cockatrice/pull/1979

**Comment by dunn** [comment]
Fixed in 152f271a7bb2b337ac6660050692343f8da3748f, thanks!
