### ISSUE TITLE
Upgrading dwarf-fortress (0.43.01 to 0.43.04) deletes all saved game data

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew-games#585]
This should not happen. Game data is stored in `data/save` relative to the game root, which is the package's `/libexec`. Other packages with data that survive between versions (e.g. python3) manage to symlink folders to common locations, like `/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages` to `/usr/local/lib/python3.5/site-packages`, so that their contents persist between upgrades.

There isn't even a warning or caveat in the dwarf-fortress package that upgrading it can delete all game data.

**Comment by dunn** [comment]
Sorry you lost data!  If the data directory can be reconfigured, we could put it in `pkgshare` instead so it persists across upgrades.

Interested in opening a PR?  Take a look at https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by jakofranko** [comment]
Are you sure that your saved game isn't in one of the previous versions? When you perform a `brew upgrade <package>` it will create a new version folder in `/usr/local/Cellar/dwarf-fortress/<version>` and it's a pretty simple process to move your saved games between versions (as long as your save is compatible between versions). Are you sure that your saved game data was deleted from the previous version?

**Comment by alexchandel** [comment]
@jakofranko Yes it was in the previous version's `data/save`, but that's the problem. After upgrading a package, it should be safe to immediately run `brew cleanup` without losing any user data.

**Comment by jakofranko** [comment]
Oh I see what you are saying. Hmmm, an interesting problem.

**Comment by MikeMcQuaid** [comment]
We'll accept a PR for this in homebrew/core where this formula now lives.
