### ISSUE TITLE
OpenMSX GLEW dependency

### ISSUE THREAD

**Issue by andreyugolnik** [Homebrew/homebrew-games#595]
OpenMSX 0.12.0 linked with GLEW 1.12.0, but 1.13.0 installed by brew.

Library not loaded: /usr/local/lib/libGLEW.1.12.0.dylib

**Comment by dunn** [comment]
Thanks for catching this!  Looks like it needed to be rebuilt against the new version of GLEW.  Should be fixed when https://github.com/Homebrew/homebrew-games/pull/597 is merged.

**Comment by dunn** [comment]
Should be fixed with a `brew update && brew upgrade`!

**Comment by andreyugolnik** [comment]
Thank you, now it works.
