### ISSUE TITLE
FUSE-emulator: no pentagon-128 roms

### ISSUE THREAD

**Issue by andreyugolnik** [Homebrew/homebrew-games#596]
Fuse-emulator 1.2.0 installed without roms for many useful speccy clones, like pentagon-128.

**Comment by dunn** [comment]
Would you be interested in opening a pull request to add them?  Take a look at https://github.com/Homebrew/brew/blob/master/share/doc/homebrew/How-To-Open-a-Homebrew-Pull-Request-(and-get-it-merged).md and let us know if you have questions!

**Comment by mistydemeo** [comment]
Closing due to lack of repsonse.
