### ISSUE TITLE
Fuego doesn't build with custom home-brew prefix

### ISSUE THREAD

**Issue by dwt** [Homebrew/homebrew-games#603]
Hi there,

I'm running home-brew out of my home directory (and also like to use it as a dependency manager for custom projects, running it out of the development directories).

Doing this I noticed that fuego isn't building for me, and that I had to add this to it's recipe to get it to build:

```diff
diff --git a/fuego.rb b/fuego.rb
index acff7ba..962d32c 100644
--- a/fuego.rb
+++ b/fuego.rb
@@ -20,7 +20,8 @@ class Fuego < Formula
     system "autoreconf", "-fvi"
     system "./configure", "--disable-dependency-tracking",
                           "--disable-silent-rules",
-                          "--prefix=#{prefix}"
+                          "--prefix=#{prefix}",
+                          "--with-boost=#{HOMEBREW_PREFIX}"
     system "make", "install"
   end
 end
```

**Comment by dunn** [comment]
Instead of `HOMEBREW_PREFIX` we should use `Formula["boost"].opt_prefix`, but if you'd like to submit a PR that'd be great!

**Comment by dwt** [comment]
Sure, will do once I get around to it.
