### ISSUE TITLE
lincity runtime bug

### ISSUE THREAD

**Issue by cxwx** [Homebrew/homebrew-games#627]
Hello everyone:
below is the BUG when I run lincity-ng install by homebrew, how can I fix it?

dyld: Library not loaded: /usr/local/opt/sdl_gfx/lib/libSDL_gfx.13.dylib
  Referenced from: /usr/local/bin/lincity-ng
  Reason: image not found
Trace/BPT trap: 5

**Comment by cxwx** [comment]
It seem the version of sdlgfx is wrong 
/usr/local/opt/sdl_gfx/lib/libSDL_gfx.15.dylib not 13

**Comment by tomyun** [comment]
Should be fixed now. Try `brew update && brew upgrade`.
