### ISSUE TITLE
Nethack4 failed to build on 10.11.6

### ISSUE THREAD

**Issue by Acroo** [Homebrew/homebrew-games#642]
Gist: https://gist.github.com/b40c918e9445282b242a5588ecc46f98

Last 15 lines:
Building from _aimake_get_option.c (rule compile_c)...                         
Compiled _aimake_get_option.o.
Building from libnethack/util/dgn_comp.l/dgn_comp.l (rule compile_lex)...
Generated libnethack/util/dgn_comp.l/dgn_comp.c.
Building from libnethack/util/lev_comp.l/lev_comp.l (rule compile_lex)...
Generated libnethack/util/lev_comp.l/lev_comp.c.
Building from libnethack/util/dgn_comp.y/dgn_comp.y (rule compile_yacc)...
Generated libnethack/util/dgn_comp.y/dgn_comp.c, libnethack/util/dgn_comp.y/dgn_comp.h.
Building from libnethack/util/lev_comp.y/lev_comp.y (rule compile_yacc)...
Generated libnethack/util/lev_comp.y/lev_comp.c, libnethack/util/lev_comp.y/lev_comp.h.
Building from libnethack/include/artilist.h/artilist.h (rule _generate_artinames_h)...
Generated libnethack/include/artinames.h/artinames.h.
Rule 'find_default_dynamic_libraries' on object 'sys:no_object' failed to match output (?^s:^(?:(?:-l|lib)[^ ]+ )?\(?(.*?/.*?(?<!aimake_1)(?:\.a|\.o|\.dylib)(?:\.[0-9]+)?)(?:\)|\([^/]*\)|\z)) at ../aimake line 9560.
 at ../aimake line 6572.
	main::__ANON__('Rule \'find_default_dynamic_libraries\' on object \'sys:no_ob...') called at ../aimake line 9560

**Comment by tomyun** [comment]
Building with gcc, instead of clang, seems to bypass this issue at least for now.

**Comment by apjanke** [comment]
Fixed by #649.
