### ISSUE TITLE
Nethack 4 breaking tap

### ISSUE THREAD

**Issue by DKuykendall** [Homebrew/homebrew-games#659]
Trying to tap the repo returns this:

Cloning into '/usr/local/Library/Taps/homebrew/homebrew-games'...
remote: Counting objects: 169, done.
remote: Compressing objects: 100% (168/168), done.
remote: Total 169 (delta 1), reused 38 (delta 0), pack-reused 0
Receiving objects: 100% (169/169), 131.54 KiB | 0 bytes/s, done.
Resolving deltas: 100% (1/1), done.
Checking connectivity... done.
Error: Invalid formula: /usr/local/Library/Taps/homebrew/homebrew-games/nethack4.rb
undefined method `rebuild' for #<BottleSpecification:0x007fa8f3aea3f0>
Error: Cannot tap homebrew/games: invalid syntax in tap!

**Comment by ilovezfs** [comment]
It means you need to `brew update`

If you already did, then you were a victim of https://twitter.com/MacHomebrew/status/763686348041641984 and need to follow those directions.
