### ISSUE TITLE
Update Supertux to version 0.5.0 (stable)

### ISSUE THREAD

**Issue by tobbi** [Homebrew/homebrew-games#680]
SuperTux 0.5.0, released on September 25. Download from https://github.com/SuperTux/supertux/releases/tag/v0.5.0

**Comment by tomyun** [comment]
Just opened a PR for the new version: #681

It was a bit tricky to have `data` dir correctly recognized by the executable and ended up with modifying `CMakeLists.txt` a bit. Please take a look and let me know if you have any comments.

**Comment by tobbi** [comment]
I am not good with CMake so I have created an issue report here: https://github.com/SuperTux/supertux/issues/614 so that someone can take a look at it.

**Comment by tomyun** [comment]
`supertux` 0.5.0 is now available for install. Thanks for your notification and fix!
