### ISSUE TITLE
linker error when brew installing stone-soup - sqlite problem?

### ISSUE THREAD

**Issue by viic** [Homebrew/homebrew-games#691]
[viic@sherlock:~]$ brew install stone-soup
==> Installing stone-soup from homebrew/games
==> Downloading https://crawl.develz.org/release/stone_soup-0.18.1.tar.xz
Already downloaded: /Users/viic/Library/Caches/Homebrew/stone-soup-0.18.1.tar.xz
==> make install DEVELOPER_DIR=/Applications/Xcode.app/Contents/Developer SDKROOT=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk SDK_VER=10.12 MARCH=x86_64 prefix=/usr/loca
Last 15 lines from /Users/viic/Library/Logs/Homebrew/stone-soup/01.make:
      SQL_DBM::finalise_query(sqlite3_stmt**) in sqldbm.o
      SQL_DBM::try_insert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in sqldbm.o
      SQL_DBM::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in sqldbm.o
      SQL_DBM::do_query(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in sqldbm.o
      SQL_DBM::nextkey() in sqldbm.o
  "_sqlite3_step", referenced from:
      SQL_DBM::try_insert(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in sqldbm.o
      SQL_DBM::remove(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in sqldbm.o
      SQL_DBM::do_query(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >*) in sqldbm.o
      SQL_DBM::nextkey() in sqldbm.o
  "_sqlite3_threadsafe", referenced from:
      databaseSystemInit() in database.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [crawl] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-games/issues

[viic@sherlock:~]$ brew --config
HOMEBREW_VERSION: 1.0.5
ORIGIN: https://github.com/Homebrew/brew
HEAD: a5565d8fd600bc2883ed76ca8708d08588d1ef3f
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: e840a660e0a4e3070b86b08a5461ea9c229c61f7
Core tap last commit: 33 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.10.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.7.0_71
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: N/A
[viic@sherlock:~]$

**Comment by tomyun** [comment]
I confirm this issue on my Sierra machine. Adding `depends_on "sqlite"` doesn't work either, but setting `BUILD_SQLITE=yes` to make its own sqlite seems to solve the issue for now.

Given that sqlite looks like causing issues for other formulae recently, there may be coming up a more general solution, I guess.

**Comment by apjanke** [comment]
Fixed by #692. Let us know if you have any further problems.
