### ISSUE TITLE
dwarf-fortress: remove retina display caveat?

### ISSUE THREAD

**Issue by sandlst** [Homebrew/homebrew-games#704]
Upon reinstalling Sierra and dwarf-fortress, I was pleasantly surprised to see x11 is no longer required; only after opening it and playing for a while did I realize I also hadn't changed the print mode to STANDARD on my retina display (usually I forget until I try to open it and it looks terrible).  I wonder if this caveat can be removed now?

**Comment by lethosor** [comment]
Yeah, SDL 1.2.15 could have fixed that. Was [this](http://www.bay12games.com/dwarves/mantisbt/view.php?id=6031) the issue you were experiencing before?

**Comment by sandlst** [comment]
Yes, that's it exactly!

**Comment by apjanke** [comment]
Removed the caveat in #746.
