### ISSUE TITLE
nethack windowtype:curses option doesn't work

### ISSUE THREAD

**Issue by alexchandel** [Homebrew/homebrew-games#709]
Despite being linked with ncurses, the nethack formula fails when the `windowtype:curses` option is given and says the only available option is `tty`.

**Comment by tomyun** [comment]
I'm not familiar with nethack, but it looks like `windowtype:curses` option is only available on 3.4.3 with [custom patch](http://nethack-curses.wikia.com/wiki/Downloads). Homebrew currently ships vanilla 3.6.0.

There are some threads mentioning the lack of (enhanced) curses interface on 3.6.0:
https://pyra-handheld.com/boards/threads/nethack-3-6-0-pandora-specific-controls-hacky-build.77187/#post-1371933
https://nethackwiki.com/wiki/Forum:A_bit_disappointed_with_3.6.0,_anyone%3F

**Comment by apjanke** [comment]
I think tomyun's right, and `windowtype:curses` was a custom mod for 3.4.3. As noted in one of those comment threads, the vanilla `tty` interface is also implemented with `curses`, which explains the linkage to ncurses.

There is a separate `nethack4` formula, which is a fork of NetHack 3.4.3 and looks like it supports a curses-style interface. You could give that a try.

Closing this as expected upstream behavior.
