### ISSUE TITLE
freeciv-2.5.5_1: Failed reading graphics file

### ISSUE THREAD

**Issue by ylluminate** [Homebrew/homebrew-games#724]
Installed freeciv via `brew install homebrew/games/freeciv` and upon completion, I attempted to launch the game with `freeciv-gtk2`.  This unfortunately failed with the following message:
```
2: Didn't find the option file. Creating a new one.
0: Failed reading graphics file "/usr/local/Cellar/freeciv/2.5.5_1/share/freeciv/misc/treaty.png": "Couldn't recognize the image file format for file '/usr/local/Cellar/freeciv/2.5.5_1/share/freeciv/misc/treaty.png'"
```

**Comment by tomyun** [comment]
That seems strange. Might be related with outdated dependencies. It has no problem with graphics loading on my local machine.

Would you follow the steps in the [troubleshooting guide](https://github.com/Homebrew/brew/blob/master/docs/Troubleshooting.md#troubleshooting) and post the details if you still have the problem? Thanks!

**Comment by tomyun** [comment]
Now we have a new version (2.5.6) in the tap (#756). Please let us know if you still encounter any issue.
