### ISSUE TITLE
revisions for icu4c 58.1 needed

### ISSUE THREAD

**Issue by ilovezfs** [Homebrew/homebrew-games#726]
- [ ] liblcf
- [ ] easyrpg-player

RE: https://github.com/Homebrew/homebrew-core/pull/6505

**Comment by tomyun** [comment]
- `liblcf` got revision update.
- `easyrpg-player` seems to work fine with no revision update after `liblcf` got merged. It has no direct dependency on `icu4c`.

**Comment by ilovezfs** [comment]
thanks @tomyun
