### ISSUE TITLE
Xmoto Unusable OSX 10.11.6

### ISSUE THREAD

**Issue by Hastradamus** [Homebrew/homebrew-games#780]
Xmoto text is not visible, so navigating the menu isn't possible which makes playing the game impossible.

[gist-log](https://gist.github.com/Hastradamus/aa6d8d70e0e4d40c35af78b14c4bce2a)

**Comment by MikeMcQuaid** [comment]
CC @mistydemeo and @tomyun to talk about this but note this formula has been migrated to homebrew/core.
