### ISSUE TITLE
Freeciv-2.5.6: Failed reading graphics file

### ISSUE THREAD

**Issue by davidgontier** [Homebrew/homebrew-games#802]
I have the same problem described in [issue #724](https://github.com/Homebrew/homebrew-games/issues/724). I installed freeciv-2.5.6 (gui-gtk-2.0) via brew, and launching freeciv-gtk2 failed:

>  2: Didn't find the option file. Creating a new one.
0: Failed reading graphics file "/usr/local/Cellar/freeciv/2.5.6/share/freeciv/misc/treaty.png": "Couldn't recognize the image file format for file '/usr/local/Cellar/freeciv/2.5.6/share/freeciv/misc/treaty.png'"

My brew is up-to-date, and I resolved all warnings of brew doctor.

**Comment by MikeMcQuaid** [comment]
Please report this to homebrew/core, this tap is deprecated.
