### ISSUE TITLE
Pioneers fails on ./configure (due to pkg-config??) on Mavericks

### ISSUE THREAD

**Issue by romen** [Homebrew/homebrew-games#87]
I'm trying to build pioneers tapped from homebrew/games.

It's giving a strange issue during ./configure related to not finding pkg-config.

brew doctor doesn't report anything that should prevent the build, and other brews build without any problem.

Here are the logs: https://gist.github.com/8015337

I also tried forcing the download of more recent versions (0.14.1 and 0.15.1) but they give exactly the same problem as the 0.12.5 version included in homebrew/games.
I was worried that I caused the problem editing the formula so I also tried to tap --repair and untap/tap homebrew/games to restore the original 0.12.5 formula.

The output is still the same, and I'm puzzling over this without any success.

**Comment by bfontaine** [comment]
Any update here?

**Comment by mistydemeo** [comment]
Closing due to lack of response. Not sure what more we can do at this point, sorry!
